### PR TITLE
BarDataSet & BarEntry rework.

### PR DESCRIPTION
**Pull request by DimitrisRK**
## PR Checklist:
- [x] I have tested this extensively and it does not break any existing behavior.
- [x] I have added/updated examples and tests for any new behavior.
- [ ] If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A, or add link to issue here]
       

## PR Description
- Converted BarEntry to interface.
- BarDataSet can now accept plain objects for BarChart, just like LineChart.
- Added support for 'xProperty' and 'yProperty' in BarDataSet.
- Added method 'initEntryData' to DataSet for handling entry objects assignments.
- Fixed BarEntry ranges not being generated.
- Fixed height position for drawn values and icons when BarChart has multiple stacks.
- Importing few of old 'BarEntry' methods into Utils since they have a general purpose and can be used by multiple classes.
- One can create multiple bar stacks by assigning array property 'yVals' inside entry object.
- One can set icon to a bar using 'icon' property.

The purpose of this is to simplify data import for BarChart, instead of generating a new BarEntry instance for each object.
One drawback is that 'BarEntry' assigned properties like isStacked, ranges, etc will also be set in objects of original array.

This is inspired from our discussion of forcing plain objects into chart dataset.
Hope this is not an overheading and you find it interesting.

### CODE REVIEW

**Comment by farfromrefug** [comment]
You are a machine! 
This is an awesome change. I LL think about the issue with isStacked and others.
Thanks

**Comment by DimitrisRK** [comment]
> This is an awesome change. I LL think about the issue with isStacked and others.

Perhaps, we could assign those properties as unmodifiable and also as hidden during object iterations, using Object.defineProperty().
Example:
`Object.defineProperty(object, 'negativeSum', {
  value: "the value",
  writable: false,
  configurable: false,
  enumerable: false
});`

It would be great if objects weren't modified, but I think there is no simple solution.

**Comment by farfromrefug** [comment]
Agree leave it like that for now!

**Comment by DimitrisRK** [comment]
> Agree leave it like that for now!

Are you talking about not using this whole update at all? If so, I'll create a new PR containing only bug fixes.

**Comment by farfromrefug** [comment]
Nono talking about keeping the object like that. About the PR did not have time to test it. Let me merge it though

**Pull request merged**
