### PR TITLE
Bar Chart implementation (Vertical only)

### PR DESCRIPTION
**Pull request by DimitrisRK**
A chart sample has been added to NS Core demo.

## PR Checklist:
- [x] I have tested this extensively and it does not break any existing behavior.
- [x] I have added/updated examples and tests for any new behavior.
- [ ] If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A, or add link to issue here]
       

## PR Description
This is the first implementation of Vertical BarChart. This is only tested in Android, so I'm not sure how it works in iOS.
A bar chart sample is included in NS Core demo.

### CODE REVIEW

**Comment by farfromrefug** [comment]
@DimitrisRK you are pretty awesome :D Will test that as soon as possible both on iOS and Android. (should work the same)

**Comment by DimitrisRK** [comment]
> @DimitrisRK you are pretty awesome :D Will test that as soon as possible both on iOS and Android. (should work the same)

Thank you. I found your efforts inspiring, so I decided to give you a hand. :) 
I'll also try to help more in the future.

One thing that bothers me about iOS compatibility. For matrix to convert bar point values to pixels, it was essential that given buffer used a native array. That is why I used method createNativeArray: https://github.com/nativescript-community/ui-chart/blob/master/src/charting/utils/Utils.ts#L721
However, even though there is native support for Android, method will return a vanilla JS array in the case of iOS. I'm not sure whether this is right or not, so any possible issues will show up during testing.

P.S. When done testing (provided that everything goes smooth), a new release would be helpful. I'm developing few apps that make use of visualizations so it's a good chance to test things more.

**Comment by farfromrefug** [comment]
Sure about the new release I can add you as a contributor so you can create "next" releases

**Comment by DimitrisRK** [comment]
> @DimitrisRK awesome works perfectly both on iOS and Android

Glad to hear that, seems I underestimated nativescript-canvas a bit. It's truly powerful. :) 
By the way, a new package version would be really helpful now. 0.0.25 is missing a bit of support for plain NativeScript apps which I added in my previous PR.

**Comment by farfromrefug** [comment]
@DimitrisRK yes it is pretty powerful. There are some crazy possibilities, next one on my list: pdf creation using canvas...
Just pushed 0.0.26.
Thanks

**Pull request merged**
